esphome:
  name: m5stack-cams3
  friendly_name: M5STACK CAMS3 5MP - ESP32S3 F16M+P8M

esp32:
  board: esp32s3box
  framework:
    type: esp-idf
    
psram:
  mode: octal
  speed: 80MHz

ota:
  - platform: esphome  

logger:

api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESP32 Camera Fallback AP"
    password: !secret ap_password

captive_portal:

i2c:
  - id: cams3_i2c
    sda: GPIO17
    scl: GPIO41
    scan: false  

esp32_camera:
  name: camera
  i2c_id: cams3_i2c
  external_clock:
    pin: GPIO11
    frequency: 20MHz
  data_pins: [GPIO6, GPIO15, GPIO16, GPIO7, GPIO5, GPIO10, GPIO4, GPIO13]
  vsync_pin: GPIO42
  href_pin: GPIO18
  pixel_clock_pin: GPIO12
  reset_pin: GPIO21
  resolution: UXGA
  jpeg_quality: 12
  max_framerate: 10 fps

esp32_camera_web_server:
- port: 8080
  mode: stream

output:
  - platform: gpio
    pin:
      number: GPIO14
      inverted: true
    id: cams3_led_output

light:
  - platform: binary
    name: "CAMS3 Indicator LED"
    output: cams3_led_output

switch:
  - platform: restart
    name: "ESP32 Camera Restart"

sensor:
  - platform: uptime
    name: "ESP32 Camera Uptime Sensor"
    
  - platform: wifi_signal
    name: "ESP32 Camera WiFi Signal"
    update_interval: 60s
